# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alfred < Formula
  desc "Your silent butler for Claude Code"
  homepage "https://github.com/hir4ta/claude-alfred"
  version "0.54.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hir4ta/claude-alfred/releases/download/v0.54.3/alfred_darwin_amd64.tar.gz"
      sha256 "c4284f7d5dac8a0a718b923f6ccff274fdd3a226233bf18880e0225c2f3d3063"

      define_method(:install) do
        bin.install "alfred"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hir4ta/claude-alfred/releases/download/v0.54.3/alfred_darwin_arm64.tar.gz"
      sha256 "0f3daa433baad980838e9d8519ee7355d35c3d48438e12b454d76456f100d7d5"

      define_method(:install) do
        bin.install "alfred"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hir4ta/claude-alfred/releases/download/v0.54.3/alfred_linux_amd64.tar.gz"
      sha256 "ecf32d22ea66e4c277797b29685cc5fd2417904551e06ecc512115cf1eefe983"
      define_method(:install) do
        bin.install "alfred"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hir4ta/claude-alfred/releases/download/v0.54.3/alfred_linux_arm64.tar.gz"
      sha256 "b16e673bf25a7f82636b1fc438dda9f97428f8585e38efe87fc6d51264c84399"
      define_method(:install) do
        bin.install "alfred"
      end
    end
  end
end
