# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alfred < Formula
  desc "Your silent butler for Claude Code"
  homepage "https://github.com/hir4ta/claude-alfred"
  version "0.58.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hir4ta/claude-alfred/releases/download/v0.58.0/alfred_darwin_amd64.tar.gz"
      sha256 "39e9ee55b07d01d3bb3b7853846b9fd589782a585e006591b873191decc26e8b"

      define_method(:install) do
        bin.install "alfred"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hir4ta/claude-alfred/releases/download/v0.58.0/alfred_darwin_arm64.tar.gz"
      sha256 "a1d9f041d463fd6e6e2c63819232e34deff9c7e72a3d083ec25f8078bf5d8c54"

      define_method(:install) do
        bin.install "alfred"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hir4ta/claude-alfred/releases/download/v0.58.0/alfred_linux_amd64.tar.gz"
      sha256 "fbe6a7d126125c5a0048f93e927f1b23cae43619d34822abc6af98b37ab13386"
      define_method(:install) do
        bin.install "alfred"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hir4ta/claude-alfred/releases/download/v0.58.0/alfred_linux_arm64.tar.gz"
      sha256 "608e29c9ae972fff551607644787ecf4936a9fe8cb0f447d4c3330a36ee21757"
      define_method(:install) do
        bin.install "alfred"
      end
    end
  end
end
